### ISSUE TITLE
I applied for a course 

### ISSUE THREAD

**Issue by mm6** [mm6/InternetOfThingsCourse#1]
Dear Sir or Madam,

  A few months ago, I applied for a Github course. I sent to you a photo of my Carnegie Mellon credentials (my CMU ID).
I am concerned since I have heard nothing back from you. Did I send my credentials to Github or was that a scam?

  Please let me know if you received my credentials or not and what is the status of my request.

Thanks,
Michael McCarthy
mm6@andrew.cmu.edu
Associate Teaching Professor
Carnegie Mellon University

**Comment by instructian** [comment]
this is a cool project i want to help
